### ISSUE TITLE
Intégration de bootstrap homogène

### ISSUE THREAD

**Issue by Orni2Thorinque** [NacimKACEL/PFE-INFO3-CONIX#2]
Utiliser bootstrap avec Angular 2 sans qu'il ne casse toute la présentation actuelle.

Déformation de la police, des marges, des paddings etc.
![sans titre](https://cloud.githubusercontent.com/assets/11539884/21331737/6bbbf77a-c644-11e6-80ee-b345f6081bbc.png)

![sans titre](https://cloud.githubusercontent.com/assets/11539884/21331783/9f1c76a8-c644-11e6-970c-f4f3aacd606b.png)

**Comment by ashfack** [comment]
Abandon de bootstrap
